Add Scp1576
Exiled-Team/Exiled-EA pull request #159
Opened 2022-12-22 14:28 UTC by louis1706

2022-12-24 22:48 UTC, Thundermaker300 commented
Is SCP-1576 permanent?

2022-12-25 17:21 UTC, iopietro commented
I don't think so.

2022-12-25 17:33 UTC, iopietro requested changes

2022-12-25 17:33 UTC, iopietro commented on Exiled.API/Features/Items/Scp1576.cs
> +    internal class Scp1576 : Usable
```suggestion
    public class Scp1576 : Usable
```

2022-12-25 17:33 UTC, iopietro commented on Exiled.API/Features/Items/Scp1576.cs
> +    using System.Threading.Tasks;
Remove the usings you don't need.

2022-12-26 01:49 UTC, Michal78900 commented
I wouldn't merge it unless we get a confirmation from NW that's SCP-1576 is permament, which will probably happen after the christmas event ends.

2022-12-26 12:05 UTC, iopietro commented
I agree.

2022-12-30 00:25 UTC, iopietro commented
I'm merging this, since @louis1706 said this is going to get permanently added.

2022-12-30 00:26 UTC, merged