Add Hume Shield API
Exiled-Team/Exiled-EA pull request #171
Opened 2022-12-26 00:28 UTC by Thundermaker300

Bonus: Player.Stamina and Player.StaminaStat

2022-12-26 00:38 UTC, Michal78900 approved these changes

2022-12-26 00:38 UTC, Michal78900 commented
Fix build errors

2022-12-26 12:29 UTC, iopietro requested changes

2022-12-26 12:29 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public float HumeShield
Define an interface for the HumeShield like the game does (`IHumeShieldedRole`) and implement it only in classes that are able to show it in the HUD. We did a similar thing with the `ISubroutinedScpRole` interface.

If you want to wrap their HumeShieldModule, you can create the "HumeShieldedRole" class which implements the IHumeShieldedRole interface, then make all role that can see the hume shield inherit from it.

2022-12-26 12:29 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        }
```suggestion
        public void PlayShieldBreakSound() 
        => new PlayerRoles.PlayableScps.HumeShield.DynamicHumeShieldController.ShieldBreakMessage(){ Target = ReferenceHub }.SendToAuthenticated();
```

2022-12-27 17:49 UTC, iopietro commented on Exiled.API/Features/Roles/FpcRole.cs
> +        public float MaxHumeShield => !IsHumeShieldedRole ? 0f : (Base as IHumeShieldedRole).HumeShieldModule.HsMax;
```suggestion
```
It's already included in the `HumeShieldBase` class, you can wrap it inside hume shield roles or just leave it as it is.

2022-12-27 17:49 UTC, iopietro commented on Exiled.API/Features/Roles/IHumeShieldRole.cs
> +        public HumeShieldModuleBase HumeShieldBase { get; }
```suggestion
        HumeShieldModuleBase HumeShieldBase { get; }
```
Interface access modifiers are public by default.

2022-12-28 00:05 UTC, iopietro commented
Fix build errors and I'll merge it.

2022-12-28 00:26 UTC, merged