PR 1393
Exiled-Team/Exiled-EA pull request #173
Opened 2022-12-26 01:34 UTC by Thundermaker300

Moved here from https://github.com/Exiled-Team/EXILED/pull/1393/files

2022-12-26 12:04 UTC, iopietro requested changes

2022-12-26 12:04 UTC, iopietro commented on Exiled.API/Features/Door.cs
> +        public string Name => Nametag is null ? GameObject.name.GetBefore(' ') : Nametag.GetName.RemoveBracketsOnEndOfName();
Unfortunately, we can't use `is null` on Unity components.

2022-12-26 12:04 UTC, iopietro commented on Exiled.API/Features/Items/Armor.cs
> +            }
Same as above: `Base.AmmoLimits` contains five elements.

2022-12-27 12:35 UTC, merged

2022-12-27 20:02 UTC, louis1706 commented on Exiled.API/Features/Door.cs
> -            return Nametag.RemoveBracketsOnEndOfName() switch
Keep Nametag