Add Player.IsNoclipPermitted
Exiled-Team/Exiled-EA pull request #188
Opened 2022-12-30 19:12 UTC by Thundermaker300

2022-12-30 22:57 UTC, iopietro requested changes

2022-12-30 22:57 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public bool IsNoclipPermitted
We should move this into the FpcRole.

2022-12-31 01:04 UTC, Thundermaker300 commented on Exiled.API/Features/Player.cs
> +        public bool IsNoclipPermitted
no, it persists between role changes

2023-01-01 23:12 UTC, Thundermaker300 commented
Resigned

2023-01-02 15:46 UTC, merged