Firearm APIs
Exiled-Team/Exiled-EA pull request #199
Opened 2022-12-31 18:59 UTC by Thundermaker300

* Firearm.IsAutomatic
* Firearm.RecoilPattern
* Firearm.FireRate and Firearm.Recoil no longer error for non-automatic weapons. Added a remark stating this

2023-01-01 23:12 UTC, Thundermaker300 commented
Resigned

2023-01-02 16:43 UTC, Thundermaker300 commented
needs tested

2023-01-04 19:30 UTC, louis1706 commented on Exiled.API/Extensions/ItemExtensions.cs
> +        public static bool IsAmmo(this ItemType item) => item.GetAmmoType() != AmmoType.None;
is not instead of !=

2023-01-04 19:30 UTC, louis1706 commented on Exiled.API/Extensions/ItemExtensions.cs
> +        public static bool IsWeapon(this ItemType type, bool checkMicro = true) => type.GetFirearmType() != FirearmType.None || (checkMicro && type == ItemType.MicroHID);
type.GetFirearmType() is not FirearmType.None || (checkMicro && type is ItemType.MicroHID);

2023-01-04 23:20 UTC, iopietro requested changes

2023-01-04 23:22 UTC, iopietro requested changes

2023-01-04 23:22 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +        public static bool IsAmmo(this ItemType item) => item.GetAmmoType() != AmmoType.None;
```suggestion
        public static bool IsAmmo(this ItemType item) => item.GetAmmoType() is not AmmoType.None;
```

2023-01-04 23:22 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +        public static bool IsWeapon(this ItemType type, bool checkMicro = true) => type.GetFirearmType() != FirearmType.None || (checkMicro && type == ItemType.MicroHID);
```suggestion
        public static bool IsWeapon(this ItemType type, bool checkMicro = true) => type.GetFirearmType() is not FirearmType.None || (checkMicro && type is ItemType.MicroHID);
```

2023-01-04 23:45 UTC, merged