Scp096Role API rework
Exiled-Team/Exiled-EA pull request #209
Opened 2023-01-02 22:36 UTC by louis1706

2023-01-03 00:36 UTC, iopietro requested changes

2023-01-03 00:36 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +            Scp096TargetsTracker = scp096TargetsTracker;
```suggestion
            if (!SubroutineModule.TryGetSubroutine(out Scp096RageCycleAbility scp096RageCycleAbility))
                Log.Debug("Scp096RageCycleAbility subroutine not found in Scp096Role::ctor");
            
            Scp096RageCycleAbility = scp096RageCycleAbility;
            
            if (!SubroutineModule.TryGetSubroutine(out Scp096RageManager scp096RageManager))
                Log.Debug("Scp096RageManager subroutine not found in Scp096Role::ctor");

            Scp096RageManager = scp096RageManager;

            if (!SubroutineModule.TryGetSubroutine(out Scp096TargetsTracker scp096TargetsTracker))
                Log.Debug("Scp096TargetsTracker not found in Scp096Role::ctor");
                
            Scp096TargetsTracker = scp096TargetsTracker;
```

2023-01-03 00:36 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        public Scp096TargetsTracker Scp096TargetsTracker { get; }
```suggestion
        public Scp096TargetsTracker TargetsTracker { get; }
```
Change the name of this property to the new one everytime it gets called above and below.

2023-01-03 00:36 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        public Scp096RageManager Scp096RageManager { get; }
```suggestion
        public Scp096RageManager RageManager { get; }
```
Change the name of this property to the new one everytime it gets called above and below.

2023-01-03 00:36 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        public Scp096RageCycleAbility Scp096RageCycleAbility { get; }
```suggestion
        public Scp096RageCycleAbility RageCycleAbility { get; }
```
Change the name of this property to the new one everytime it gets called above and below.

2023-01-03 00:36 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        public void ClearTarget() => Scp096TargetsTracker.ClearAllTargets();
```suggestion
        public void ClearTargets() => Scp096TargetsTracker.ClearAllTargets();
```

2023-01-03 22:21 UTC, louis1706 commented
i would like to keep all the Error Check for all the Beta in case of getting issue with them

2023-01-04 13:47 UTC, iopietro commented
Ok, seems about right.

2023-01-04 14:40 UTC, iopietro requested changes

2023-01-04 14:40 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        /// .
Some comments are missing.

2023-01-04 14:40 UTC, iopietro commented on Exiled.API/Features/Roles/Scp096Role.cs
> +        public void ClearTarget() => TargetsTracker.ClearAllTargets();
```suggestion
        public void ClearTargets() => TargetsTracker.ClearAllTargets();
```

2023-01-04 14:40 UTC, iopietro commented on Exiled.API/Features/Roles/Scp106Role.cs
> +            return true;
```suggestion
            HuntersAtlasAbility._syncPos = position;

            if (Vigor > cost)
                return false;

            HuntersAtlasAbility._estimatedCost = cost;
            HuntersAtlasAbility.SetSubmerged(true);

            return true;
```

2023-01-04 14:40 UTC, iopietro commented on Exiled.API/Features/Roles/Scp939Role.cs
> +        /// Removes all recordings of player voices. Provide an optional target to remove all the recordings of a single player.
Where's the optional target?

2023-01-04 18:15 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp049Role.cs
> +        public Player RecallingPlayer => Player.Get(ResurrectAbility.CurRagdoll?.Info.OwnerHub);
it's will prevent NRE no ?

2023-01-04 18:22 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp939Role.cs
> +        /// Removes all recordings of player voices. Provide an optional target to remove all the recordings of a single player.
miss to modify the comment

2023-01-04 18:37 UTC, Thundermaker300 approved these changes

2023-01-04 23:18 UTC, merged